"""Regenerate the API and database reference docs from the real code/schema.

Writes:
  docs/api/openapi.json     -- FastAPI's OpenAPI document (no DB needed)
  docs/API_REFERENCE.md     -- endpoint index grouped by tag
  docs/DATABASE_SCHEMA.md   -- tables, columns and RLS status, read from a
                               migrated database (needs SERVICE_DATABASE_URL)

Usage (from the repo root, after `alembic upgrade head`):

    python scripts/generate_reference_docs.py            # API + schema
    python scripts/generate_reference_docs.py --api-only # no database needed

Never hand-edit the generated files; re-run this script instead.
"""
from __future__ import annotations

import argparse
import json
import os
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"


def write_api_docs() -> int:
    from app.main import app

    spec = app.openapi()
    (DOCS / "api").mkdir(parents=True, exist_ok=True)
    (DOCS / "api" / "openapi.json").write_text(json.dumps(spec, indent=2, sort_keys=True) + "\n")

    by_tag: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    count = 0
    for path, methods in sorted(spec["paths"].items()):
        for method, op in sorted(methods.items()):
            tag = (op.get("tags") or ["untagged"])[0]
            summary = (op.get("summary") or "").replace("|", "\\|")
            by_tag[tag].append((method.upper(), path, summary))
            count += 1

    lines = [
        "# HarborIQ API Reference (generated)",
        "",
        "Generated by `scripts/generate_reference_docs.py` from the FastAPI app. "
        "Do not edit by hand. The machine-readable contract is "
        "[`docs/api/openapi.json`](api/openapi.json); a running server also serves "
        "interactive docs at `/docs` and `/redoc`.",
        "",
        f"API version: `{spec['info'].get('version', 'unknown')}` · Operations: **{count}**",
        "",
        "Authentication: staff endpoints require a bearer access token (or the httpOnly "
        "cookie session plus CSRF header). Portal and public endpoints are authenticated "
        "by scoped, hashed, expiring tokens in the path. Webhooks verify provider "
        "signatures.",
        "",
    ]
    for tag in sorted(by_tag):
        lines += [f"## {tag}", "", "| Method | Path | Summary |", "|---|---|---|"]
        lines += [f"| {m} | `{p}` | {s} |" for m, p, s in by_tag[tag]]
        lines.append("")
    (DOCS / "API_REFERENCE.md").write_text("\n".join(lines))
    return count


def write_schema_doc() -> int:
    from sqlalchemy import create_engine, text

    url = os.environ["SERVICE_DATABASE_URL"]
    engine = create_engine(url, future=True)
    with engine.connect() as conn:
        revision = conn.execute(text("SELECT version_num FROM alembic_version")).scalar()
        tables = conn.execute(
            text(
                """
                SELECT c.relname AS name, c.relrowsecurity AS rls, c.relforcerowsecurity AS forced
                  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                 WHERE n.nspname = 'public' AND c.relkind = 'r'
                   AND c.relname <> 'alembic_version'
                 ORDER BY c.relname
                """
            )
        ).all()
        columns = conn.execute(
            text(
                """
                SELECT table_name, column_name, data_type, udt_name, is_nullable,
                       column_default, is_generated
                  FROM information_schema.columns
                 WHERE table_schema = 'public'
                 ORDER BY table_name, ordinal_position
                """
            )
        ).all()
        policies = conn.execute(
            text("SELECT tablename, policyname FROM pg_policies WHERE schemaname = 'public'")
        ).all()
    engine.dispose()

    cols: dict[str, list] = defaultdict(list)
    for row in columns:
        cols[row.table_name].append(row)
    pols: dict[str, list[str]] = defaultdict(list)
    for row in policies:
        pols[row.tablename].append(row.policyname)

    lines = [
        "# HarborIQ Database Schema (generated)",
        "",
        "Generated by `scripts/generate_reference_docs.py` from a database migrated to "
        f"Alembic revision **`{revision}`**. Do not edit by hand.",
        "",
        "Tenant isolation: tenant tables enable and FORCE PostgreSQL row-level security; "
        "the application connects as `harboriq_app` (RLS enforced) and sets "
        "`app.current_company_id` per transaction via `app/db/tenant.py`. Platform-level "
        "tables (webhook idempotency, marketing leads, plans) are service-role only. "
        "Source of truth: `alembic/versions/` and `alembic/sql/`.",
        "",
        "| Table | RLS | Forced | Policies |",
        "|---|---|---|---|",
    ]
    for t in tables:
        lines.append(
            f"| `{t.name}` | {'yes' if t.rls else 'no'} | {'yes' if t.forced else 'no'} | "
            f"{', '.join(sorted(pols.get(t.name, []))) or '—'} |"
        )
    lines.append("")
    for t in tables:
        lines += [f"## `{t.name}`", "", "| Column | Type | Null | Default |", "|---|---|---|---|"]
        for c in cols[t.name]:
            typ = c.udt_name if c.data_type == "USER-DEFINED" else c.data_type
            default = "generated" if c.is_generated == "ALWAYS" else (c.column_default or "")
            default = default.replace("|", "\\|")[:60]
            lines.append(f"| `{c.column_name}` | {typ} | {c.is_nullable} | {default} |")
        lines.append("")
    (DOCS / "DATABASE_SCHEMA.md").write_text("\n".join(lines))
    return len(tables)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--api-only", action="store_true")
    args = parser.parse_args()
    print(f"API operations documented: {write_api_docs()}")
    if not args.api_only:
        print(f"Tables documented: {write_schema_doc()}")


if __name__ == "__main__":
    main()
