#!/usr/bin/env python3
"""
Generate a U.S. Copyright Office deposit-copy text file for HarborIQ's
source code, using the "first 10 and last 10 pages" trade-secret deposit
option under 37 C.F.R. 202.20(c)(2)(vii)(A)(1) -- the simplest of the three
recognized methods for depositing a computer program that contains trade
secret / confidential material, since it requires no manual redaction.

"Page" is treated as 40 lines of code, per Copyright Office Circular 61
("As a rule of thumb, 40 lines of code may be considered equal to a
page. Thus, the first 1000 and last 1000 lines of code would be an
acceptable electronic copy.") -- see
https://www.copyright.gov/eco/help-deposit.html

This concatenates the program's real source files (backend Python, then
frontend TypeScript/TSX) in a fixed, deterministic order to form one
continuous "source code" listing, then extracts the first 1000 and last
1000 lines of that combined listing. It deliberately excludes tests,
autogenerated Alembic migration boilerplate, lockfiles, and vendored/
dependency directories, since those are not the "source code actually
written by the author" in the sense Circular 61 means.

Run from the repo root:
    python scripts/generate_copyright_deposit.py

Output: docs/copyright_deposit_first10_last10.txt
Convert to PDF (Copyright Office prefers PDF) with any of:
    pandoc docs/copyright_deposit_first10_last10.txt -o docs/copyright_deposit_first10_last10.pdf
or open the .txt and use "Print to PDF" from any editor.
"""

from __future__ import annotations

import pathlib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
LINES_PER_PAGE = 40
PAGES_EACH_END = 10
LINES_EACH_END = LINES_PER_PAGE * PAGES_EACH_END  # 400

BACKEND_EXCLUDE_DIRS = {".venv", "__pycache__", "alembic/versions", "alembic/sql"}
BACKEND_INCLUDE_EXT = {".py"}
BACKEND_EXCLUDE_NAME_PARTS = ("test_", "_test.py", "conftest.py")

FRONTEND_EXCLUDE_DIRS = {"node_modules", "dist", "coverage"}
FRONTEND_INCLUDE_EXT = {".ts", ".tsx"}
FRONTEND_EXCLUDE_NAME_PARTS = (".test.", ".spec.")


def _iter_files(root: pathlib.Path, include_ext: set[str], exclude_dirs: set[str], exclude_name_parts: tuple[str, ...]):
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix not in include_ext:
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        if any(f"/{d}/" in f"/{rel}/" or rel.startswith(f"{d}/") for d in exclude_dirs):
            continue
        if any(part in path.name for part in exclude_name_parts):
            continue
        yield path


def build_listing() -> list[str]:
    lines: list[str] = []
    backend_root = REPO_ROOT / "app"
    frontend_root = REPO_ROOT / "frontend" / "src"

    for path in _iter_files(backend_root, BACKEND_INCLUDE_EXT, BACKEND_EXCLUDE_DIRS, BACKEND_EXCLUDE_NAME_PARTS):
        rel = path.relative_to(REPO_ROOT).as_posix()
        lines.append(f"# ===== FILE: {rel} =====")
        lines.extend(path.read_text(encoding="utf-8", errors="replace").splitlines())
        lines.append("")

    for path in _iter_files(frontend_root, FRONTEND_INCLUDE_EXT, FRONTEND_EXCLUDE_DIRS, FRONTEND_EXCLUDE_NAME_PARTS):
        rel = path.relative_to(REPO_ROOT).as_posix()
        lines.append(f"// ===== FILE: {rel} =====")
        lines.extend(path.read_text(encoding="utf-8", errors="replace").splitlines())
        lines.append("")

    return lines


def read_version() -> str:
    pyproject = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    for line in pyproject.splitlines():
        if line.strip().startswith("version"):
            return line.split("=", 1)[1].strip().strip('"')
    return "unknown"


def read_copyright_notice() -> str:
    license_path = REPO_ROOT / "LICENSE"
    if license_path.exists():
        for line in license_path.read_text(encoding="utf-8").splitlines():
            if "Copyright" in line:
                return line.strip()
    return "(no copyright notice found)"


def main() -> None:
    listing = build_listing()
    total = len(listing)
    first = listing[:LINES_EACH_END]
    last = listing[-LINES_EACH_END:] if total > LINES_EACH_END else []

    out_path = REPO_ROOT / "docs" / "copyright_deposit_first10_last10.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    divider = "=" * 70
    header = (
        "TITLE: HarborIQ\n"
        f"VERSION: {read_version()}\n"
        "Source Code Deposit Copy -- Prepared for U.S. Copyright Office\n"
        "registration under the trade-secret deposit option: first 10 and\n"
        "last 10 pages (40 lines/page equivalent, per Circular 61 /\n"
        "37 C.F.R. 202.20(c)(2)(vii)(A)(1)).\n"
        f"Total lines in full combined source listing: {total}\n"
        "This is a partial deposit by design -- it is NOT the complete program.\n"
        "\n"
        "COPYRIGHT NOTICE (from LICENSE file of the version being registered):\n"
        f"{read_copyright_notice()}\n"
        "\n"
        f"{divider}\n"
        f"FIRST {PAGES_EACH_END} PAGES ({LINES_EACH_END} LINES)\n"
        f"{divider}\n"
    )
    middle_notice = (
        f"\n\n{divider}\n"
        f"[... {max(total - 2 * LINES_EACH_END, 0)} lines omitted per trade-secret deposit rules ...]\n"
        f"{divider}\n\n"
        f"{divider}\n"
        f"LAST {PAGES_EACH_END} PAGES ({LINES_EACH_END} LINES)\n"
        f"{divider}\n"
    )

    with out_path.open("w", encoding="utf-8") as f:
        f.write(header)
        f.write("\n".join(first))
        f.write(middle_notice)
        f.write("\n".join(last))
        f.write("\n")

    print(f"Wrote {out_path} ({total} total lines in combined source; "
          f"{len(first)} first + {len(last)} last lines deposited)")


if __name__ == "__main__":
    main()
